# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            rjpdasilva
tagline:          'My GitHub Pages website'
description:      'My <a href="https://pages.github.com/">GitHub Pages</a> website'
url:              https://rjpdasilva.github.io

author:
  copy:           '2017'
  name:           'Ricardo Silva'
  url:            https://rjpdasilva.github.io

paginate:         1
paginate_path:    "/bloglist/page:num/"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/rjpdasilva/rjpdasilva.github.io
